import { Badge } from "@/components/ui/badge";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { WorkoutUI } from "@/types/workouts";
import { Clock, Dumbbell, Zap } from "lucide-react";
import Link from "next/link";

interface SummaryWorkoutCardProps {
	/** The mapped workout data object containing display-ready statistics. */
	workout: WorkoutUI;
}

/**
 * Summarized view of a single completed workout session.
 * - Information Density: Packs volume, duration, and muscle groups into a compact card.
 */
export const SummaryWorkoutCard = ({ workout }: SummaryWorkoutCardProps) => {
	/** * Destructuring UI-ready fields provided by the mapWorkoutForUI helper.
	 */
	const { name, displayDate, duration_seconds, total_volume, muscles, totalSets } = workout;

	/** * Unit Conversion:
	 * Converts raw duration seconds from the database into a readable minute format
	 */
	const durationMinutes = Math.floor(duration_seconds / 60);

	return (
		<Link href={`/dashboard/workouts/${workout.id}`} className="block group transition-all active:scale-[0.98]">
			<Card className="bg-secondary/10 border-primary/10 overflow-hidden mb-2  transition-transform hover:border-primary/30 group">
				<CardHeader className="p-4 pb-2">
					<div className="flex justify-between items-start">
						<div>
							{/* Displaying the localized date generated by the server-side utility or mapper */}
							<p className="text-[10px] text-muted-foreground uppercase tracking-widest font-mono mb-1">{displayDate}</p>
							<CardTitle className="text-xl font-black italic uppercase tracking-tighter group-hover:text-primary transition-colors">
								{name}
							</CardTitle>
						</div>
						{/* Placeholder for progress tracking logic (currently static) */}
						<Badge variant="secondary" className="bg-primary/20 text-primary border-none text-[10px] font-bold">
							PROGRESS +?%
						</Badge>
					</div>
				</CardHeader>
				<CardContent className="p-4 pt-2">
					{/* Primary Stats: Duration, Volume, and Set Count */}
					<div className="flex gap-4 mb-4">
						<div className="flex items-center gap-1.5 text-xs font-bold text-muted-foreground uppercase">
							<Clock size={14} className="text-primary" />
							{durationMinutes} min
						</div>
						<div className="flex items-center gap-1.5 text-xs font-bold text-muted-foreground uppercase">
							<Dumbbell size={14} className="text-primary" />
							{total_volume} kg
						</div>
						<div className="flex items-center gap-1.5 text-xs font-bold text-muted-foreground uppercase">
							<Zap size={14} className="text-primary" />
							{totalSets} sets
						</div>
					</div>

					{/** * Dynamic Muscle Badges:
					 * Renders a unique badge for each muscle group targeted in the session.
					 */}
					<div className="flex flex-wrap gap-1">
						{muscles.map((m) => (
							<Badge
								key={m}
								variant="outline"
								className="text-[9px] uppercase border-primary/20 bg-primary/5 text-muted-foreground font-bold tracking-widest"
							>
								{m}
							</Badge>
						))}
					</div>
				</CardContent>
			</Card>
		</Link>
	);
};
