/**
 * @fileoverview Workout Domain Type System.
 * Defines the relational models for training sessions and performance sets.
 * This system bridges the gap between Supabase's PostgREST joins and the
 * high-performance presentation layer.
 * @module types/workouts
 */

/**
 * Represents the raw workout session model as stored in the database.
 * * @description
 * This interface directly reflects the `public.workouts` table schema. It acts as
 * the primary container for a single training event, tracking global metrics
 * and session state.
 * * **Relational Integrity:**
 * Maintains a one-to-many relationship with `WorkoutSet` line items.
 * @interface Workout
 * @property {string} id - Unique UUID identifier for the session (Primary Key).
 * @property {string} user_id - Foreign key reference to the authenticated user.
 * @property {string} name - User-defined label for the workout (e.g., "Leg Day Hypertrophy").
 * @property {number} duration_seconds - Total elapsed time of the session in seconds.
 * @property {number} total_volume - Cumulative tonnage moved during the session.
 * Calculated as: $$V_{total} = \sum_{i=1}^{n} (weight_i \times reps_i)$$
 * @property {string} started_at - ISO timestamp marking the beginning of the session.
 * @property {string | null} completed_at - ISO timestamp of finalization. Null if the session is still active.
 * @property {string} status - Discrete state used to drive dashboard visibility logic.
 * @property {WorkoutSet[]} workout_sets - Array of sets retrieved via nested relational joins.
 */
export interface Workout {
	id: string;
	user_id: string;
	name: string;
	duration_seconds: number;
	total_volume: number;
	started_at: string;
	completed_at: string | null;
	status: "in_progress" | "completed";
	workout_sets: WorkoutSet[];
}

/**
 * Represents an individual exercise set within a workout session.
 * * @description
 * The granular unit of performance tracking. Includes nested exercise metadata
 * retrieved through Supabase relational joins to minimize API round-trips.
 * @interface WorkoutSet
 * @property {string} id - Unique UUID identifier for the specific set entry.
 * @property {string} workout_id - Foreign key linking back to the parent `Workout` session.
 * @property {string} exercise_id - Foreign key reference to the specific movement in the library.
 * @property {number} weight - The load used for this specific set in kilograms.
 * @property {number} reps - Number of repetitions successfully completed.
 * @property {number} set_order - Chronological position used to maintain set sequence in the UI.
 * @property {string} created_at - ISO timestamp of record creation.
 * @property {Object | null} exercises - Nested metadata. Prevents N+1 query problems by fetching name and muscle group in the primary query.
 */
export interface WorkoutSet {
	id: string;
	workout_id: string;
	exercise_id: string;
	weight: number;
	reps: number;
	set_order: number;
	created_at: string;
	exercises: {
		name: string;
		muscle_group: string;
	} | null;
}

/**
 * Extended workout model optimized for the presentation layer (DTO).
 * * @description
 * A flattened and pre-calculated data transfer object generated by mapping utilities.
 * Designed to provide "ready-to-render" statistics for cards and history feeds,
 * ensuring 60fps scrolling by moving calculations out of the render cycle.
 * @interface WorkoutUI
 * @property {string} id - Primary database identifier for navigation.
 * @property {string} name - Display name of the session.
 * @property {string} displayDate - Localized and formatted date string (e.g., "22 lut 2026").
 * @property {number} duration_seconds - Raw duration for time formatting utilities.
 * @property {number} total_volume - Pre-aggregated total weight moved.
 * @property {string[]} muscles - Unique collection of muscle groups targeted (e.g., ["Chest", "Shoulders"]).
 * @property {number} exerciseCount - Total number of unique movements performed.
 * @property {number} totalSets - Total count of sets recorded across all movements.
 */
export interface WorkoutUI {
	id: string;
	name: string;
	displayDate: string;
	duration_seconds: number;
	total_volume: number;
	muscles: string[];
	exerciseCount: number;
	totalSets: number;
}

/**
 * Represents a paginated data slice for the workout history feed.
 * * @description
 * This model is the core contract for the **Infinite Loading Pattern**.
 * It encapsulates a single "page" of mapped UI records along with the
 * absolute total count of sessions available in the database.
 * * **Use Cases:**
 * 1. **SSR Hydration**: Seeds the TanStack Query cache with the first page + global metadata.
 * 2. **Client-side Fetching**: Serves as the return type for `useInfiniteQuery` page parameters.
 * @interface WorkoutPage
 * @property {WorkoutUI[]} items - Array of formatted workout summaries for the current page.
 * @property {number} totalCount - The exact total number of workouts in the database for the current user filter.
 */
export interface WorkoutPage {
	items: WorkoutUI[];
	totalCount: number;
}
