/**
 * Represents the raw workout session model as stored in the database.
 * Directly reflects the `public.workouts` table schema.
 */
export interface Workout {
	/** Unique UUID identifier for the session. */
	id: string;
	/** Foreign key reference to the authenticated user (auth.users). */
	user_id: string;
	/** User-defined name of the workout, e.g., "Push Day". */
	name: string;
	/** Total duration of the session in seconds. */
	duration_seconds: number;
	/** Cumulative weight moved during the session (weight * reps). */
	total_volume: number;
	/** Timestamp of when the session started. */
	started_at: string;
	/** Timestamp of when the session ended. Null if session is active. */
	completed_at: string | null;
	/** Current state of the session used to drive UI logic. */
	status: "in_progress" | "completed";
	/** Array of sets performed during this workout session, retrieved via nested joins. */
	workout_sets: WorkoutSet[];
}

/**
 * Represents an individual exercise set within a workout session.
 * Includes nested exercise metadata retrieved through Supabase relational joins.
 */
export interface WorkoutSet {
	/** Unique UUID identifier for the set entry. */
	id: string;
	/** Reference to the parent workout session. */
	workout_id: string;
	/** Reference to the specific exercise performed. */
	exercise_id: string;
	/** The load/weight used for this specific set. */
	weight: number;
	/** Number of repetitions successfully completed. */
	reps: number;
	/** The chronological position of the set within the workout flow. */
	set_order: number;
	/** Timestamp of record creation. */
	created_at: string;
	/** * Nested exercise metadata.
	 * Prevents redundant API calls by fetching name and muscle group in the primary query.
	 */
	exercises: {
		name: string;
		muscle_group: string;
	} | null;
}

/**
 * Extended workout model optimized for the presentation layer.
 * Generated by the mapping utility to provide pre-calculated statistics and formatted strings.
 */
export interface WorkoutUI {
	/** Primary database ID. */
	id: string;
	/** Display name of the session. */
	name: string;
	/** User-friendly date string (e.g., "Feb 22, 2026"). */
	displayDate: string;
	/** Total session duration in seconds. */
	duration_seconds: number;
	/** Calculated total training volume. */
	total_volume: number;
	/** List of unique muscle groups targeted during the session. */
	muscles: string[];
	/** Number of unique exercises performed in this session. */
	exerciseCount: number;
	/** Total number of sets recorded across all exercises. */
	totalSets: number;
}
